//const asyncHandler = ()=>{}
//const asyncHandler = (func)=>{()=>{}}
//const asyncHandler = (func)=>async()=>{}

//Creating a try catch wrapper with (next) - a middleware
// const asyncHandler = (fn) => async (req, res, next) => {
//     try {
//         await fn(req, res, next)
//     } catch (error) {
//         res.status(err.code || 500).json({
//             success: false,
//             message: err.message
//         })
//     }
// }

//Creating a Promise wrapper
const asyncHandler = (requestHandler) => {
    (req, res, next) => {
        Promise.resolve(requestHandler(req, res, next)).catch((err) => next(err))
    }
}

export {asyncHandler}